# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa07d992577237288e29e121250e7d5067788d92a652fa26d40c16b3e3b58fc611728ece8a985b8618477859b3ef214ded5892f2ab0c73d4de4f265f2d24f0c

test:
  secret_key_base: 09bcb072efbed1f1b0665be6bab8f4282227d622e8a6280a232fd3a4788055bd8667318fa9ce1f4de6baa5957093d03b2bfadb4520d6895dc26ed4937b56a480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
